services:
  db:
    image: postgres:16
    environment:
     POSTGRES_DB: empdb
     POSTGRES_USER: empuser
     POSTGRES_PASSWORD: emppass
    volumes:
      - ./backend/models.sql:/app/models.sql
  backend:
    image: ${BACKEND_IMAGE}
    build: ./backend
    ports:
      - "5000:5000"

  frontend:
    image: ${FRONTEND_IMAGE}
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
