db:
  image: postgres:16
  container_name: web_applications-db
  environment:
    POSTGRES_USER: empuser
    POSTGRES_PASSWORD: emppassword
    POSTGRES_DB: empdb
  volumes:
    - pgdata:/var/lib/postgresql/data
    - ./backend/models.sql:/docker-entrypoint-initdb.d/models.sql
  networks:
    - webnet
