services:
  db:
    image: postgres:16
    container_name: web_applications-db
    environment:
      POSTGRES_USER: empuser
      POSTGRES_PASSWORD: emppassword
      POSTGRES_DB: empdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: ${BACKEND_IMAGE}:${IMAGE_TAG}
    container_name: web_applications-backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: empuser
      DB_PASSWORD: emppassword
      DB_NAME: empdb
    ports:
      - "5001:5001"

  frontend:
    image: ${FRONTEND_IMAGE}:${IMAGE_TAG}
    container_name: web_applications-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
