version: "3.9"

services:
  db:
    image: postgres:16
    container_name: web_applications-db
    environment:
      POSTGRES_USER: empuser
      POSTGRES_PASSWORD: emppass
      POSTGRES_DB: empdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: ${BACKEND_IMAGE}
    container_name: web_applications-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/employee_db
    ports:
      - "5001:5000"

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: web_applications-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pgdata:
